xdescribe('groupUsersByAirportCode', () => {
  const {
    groupUsersByAirportCode,
  } = require('../../lambda/algo/bookingOptions/getBookingOptions.js');
  it('groups users by airport code', () => {
    const users = [
      { id: 1, building: { airportCode: 'SEA' } },
      { id: 2, building: { airportCode: 'YVR' } },
      { id: 3, building: { airportCode: 'SEA' } },
      { id: 4, building: { airportCode: 'YVR' } },
    ];
    const result = groupUsersByAirportCode(users);
    expect(result).toEqual({
      SEA: [
        { id: 1, building: { airportCode: 'SEA' } },
        { id: 3, building: { airportCode: 'SEA' } },
      ],
      YVR: [
        { id: 2, building: { airportCode: 'YVR' } },
        { id: 4, building: { airportCode: 'YVR' } },
      ],
    });
  });
});
xdescribe('groupUsersByBuilding', () => {
  const {
    groupUsersByBuilding,
  } = require('../../lambda/algo/bookingOptions/getBookingOptions.js');
  it('groups users by building Id', () => {
    const users = [
      { id: 1, buildingId: '32' },
      { id: 2, buildingId: '41' },
      { id: 3, buildingId: '74' },
      { id: 4, buildingId: '32' },
      { id: 5, buildingId: '41' },
    ];
    const result = groupUsersByBuilding(users);
    expect(result).toEqual({
      '32': [
        { id: 1, buildingId: '32' },
        { id: 4, buildingId: '32' },
      ],
      '41': [
        { id: 2, buildingId: '41' },
        { id: 5, buildingId: '41' },
      ],
      '74': [{ id: 3, buildingId: '74' }],
    });
  });
});
xdescribe('findRoomsOnMultipleFloors', () => {
  const {
    findRoomsOnMultipleFloors,
  } = require('../../lambda/algo/bookingOptions/getBookingOptions.js');
  const user1 = {
    name: 'user1',
    floorNumber: 1,
  };
  const user2 = {
    name: 'user2',
    floorNumber: 1,
  };
  const user3 = {
    name: 'user3',
    floorNumber: 2,
  };
  const user4 = {
    name: 'user4',
    floorNumber: 2,
  };
  const user5 = {
    name: 'user5',
    floorNumber: 3,
  };
  const user6 = {
    name: 'user6',
    floorNumber: 4,
  };
  const user7 = {
    name: 'user7',
    floorNumber: 5,
  };
  const room1 = {
    id: 'room1',
    floorNumber: 1,
    number: '101',
    capacity: 2,
    capabilities: ['AV'],
    BookingRecords: [],
  };
  const room2 = {
    id: 'room2',
    floorNumber: 2,
    number: '101',
    capacity: 2,
    capabilities: ['AV'],
    BookingRecords: [],
  };
  const room3 = {
    id: 'room3',
    floorNumber: 10,
    number: '101',
    capacity: 2,
    capabilities: [],
    BookingRecords: [],
  };
  const room4 = {
    id: 'room4',
    floorNumber: 10,
    number: '101',
    capacity: 1,
    capabilities: [],
    BookingRecords: [],
  };

  it('should assign 7 users into 4 rooms and under or equal to total capacity of 7', () => {
    // input
    const users = [user1, user2, user3, user4, user5, user6, user7];
    const rooms = [room1, room2, room3, room4];
    // output
    const assgined1 = {
      rooms: [room1, room2, room3],
      users: [user1, user2],
    };
    const assgined2 = {
      rooms: [room2, room3],
      users: [user3, user4],
    };
    const assgined3 = {
      rooms: [room3],
      users: [user5, user6],
    };
    const assgined4 = {
      rooms: [room4],
      users: [user7],
    };
    const result = findRoomsOnMultipleFloors(users, rooms, ['AV']);
    expect(result).toEqual([assgined1, assgined2, assgined3, assgined4]);
  });
  it('should throw an error for 7 users which is over the total capacity of 6', () => {
    // input
    const users = [user1, user2, user3, user4, user5, user6, user7];
    const rooms = [room1, room2, room3];

    try {
      findRoomsOnMultipleFloors(users, rooms, ['AV']);
      // If the function doesn't throw an error, fail the test
      fail('Expected an error to be thrown, but none was thrown.');
    } catch (error: any) {
      // Verify that the error message matches the expected message
      expect(error.message).toEqual(
        'No suitable rooms found for the given user capacity.'
      );
    }
  });
});
xdescribe('findAvailableRooms', () => {
  const {
    findAvailableRooms,
  } = require('../../lambda/algo/bookingOptions/getBookingOptions.js');
  const room1 = {
    id: 'room1',
    floorNumber: 1,
    number: '101',
    capacity: 2,
    capabilities: ['VC', 'AV'],
    BookingRecords: [],
  };
  const room2 = {
    id: 'room2',
    floorNumber: 2,
    number: '101',
    capacity: 1,
    capabilities: ['AV'],
    BookingRecords: [],
  };
  const room3 = {
    id: 'room3',
    floorNumber: 10,
    number: '101',
    capacity: 1,
    capabilities: [],
    BookingRecords: [],
  };
  const room4 = {
    id: 'room4',
    floorNumber: 10,
    number: '101',
    capacity: 2,
    capabilities: ['AV'],
    BookingRecords: [],
  };
  const room5 = {
    id: 'room5',
    floorNumber: 10,
    number: '101',
    capacity: 3,
    capabilities: [],
    BookingRecords: [],
  };
  const building1 = {
    id: 'building1',
    airportCode: 'SEA',
    number: 1,
    name: 'AWS building 1',
    longitude: -122.308,
    latitude: 47.45,
    rooms: [room1, room2, room3],
  };
  const building2 = {
    id: 'building2',
    airportCode: 'SEA',
    number: 1,
    name: 'AWS building 2',
    longitude: -122.308,
    latitude: 47.45,
    rooms: [room4, room5],
  };
  const user1 = {
    name: 'user1',
    floorNumber: 1,
    buildingId: 'building1',
    building: building1,
  };
  const user2 = {
    name: 'user2',
    floorNumber: 2,
    buildingId: 'building1',
    building: building1,
  };
  const user3 = {
    name: 'user3',
    floorNumber: 6,
    buildingId: 'building1',
    building: building1,
  };
  const user4 = {
    name: 'user4',
    floorNumber: 1,
    buildingId: 'building2',
    building: building2,
  };
  const user5 = {
    name: 'user5',
    floorNumber: 5,
    buildingId: 'building2',
    building: building2,
  };
  it('should group users into 2 groups and find available rooms', () => {
    // input
    const users = [user1, user2, user3, user4, user5];
    const requiredCapabilities = ['VC', 'AV'];
    // output
    const assgined1 = {
      rooms: [room1],
      users: [user1, user2],
    };
    const assgined2 = {
      rooms: [room3, room2],
      users: [user3],
    };
    const assgined3 = {
      rooms: [room5, room4],
      users: [user4, user5],
    };
    const result = findAvailableRooms(users, requiredCapabilities);
    expect(result).toEqual([[assgined1, assgined2], [assgined3]]);
  });
});
xdescribe('sortRoomsByScore', () => {
  const {
    sortRoomsByScore,
  } = require('../../lambda/algo/bookingOptions/getBookingOptions.js');
  xit('should return rooms that matches capacity the most', () => {
    const room1 = {
      number: '1',
      floorNumber: 1,
      capacity: 5,
      capabilities: ['AV', 'VC'],
    };
    const room2 = {
      number: '1',
      floorNumber: 1,
      capacity: 6,
      capabilities: ['AV', 'VC'],
    };
    const room3 = {
      number: '1',
      floorNumber: 1,
      capacity: 7,
      capabilities: ['AV', 'VC'],
    };
    const room4 = {
      number: '1',
      floorNumber: 1,
      capacity: 7,
      capabilities: ['AV', 'VC'],
    };
    const room5 = {
      number: '1',
      floorNumber: 1,
      capacity: 70,
      capabilities: ['AV', 'VC'],
    };
    const rooms = [room1, room2, room3, room4, room5];
    const requiredCapabilities = ['AV', 'VC'];
    const targetFloor = 1;
    const result = sortRoomsByScore(rooms, requiredCapabilities, targetFloor);
    expect(result).toEqual([room1, room2, room3, room4, room5]);
  });
  xit('should return rooms that matches capabilities the most', () => {
    const room1 = {
      number: '1',
      floorNumber: 1,
      capacity: 1,
      capabilities: ['AV', 'VC'],
    };
    const room2 = {
      number: '1',
      floorNumber: 1,
      capacity: 1,
      capabilities: ['AV'],
    };
    const room3 = {
      number: '1',
      floorNumber: 1,
      capacity: 1,
      capabilities: ['VC'],
    };
    const room4 = {
      number: '1',
      floorNumber: 1,
      capacity: 1,
      capabilities: [],
    };
    const room5 = {
      number: '1',
      floorNumber: 1,
      capacity: 1,
      capabilities: [],
    };
    const rooms = [room1, room2, room3, room4, room5];
    const requiredCapabilities = ['AV', 'VC'];
    const targetFloor = 1;
    const result = sortRoomsByScore(rooms, requiredCapabilities, targetFloor);
    expect(result).toEqual([room1, room2, room3, room4, room5]);
  });
  xit('should return mixed: dramatic value for one room', () => {
    const room1 = {
      number: '1',
      floorNumber: 50,
      capacity: 30,
      capabilities: [],
    };
    const room2 = {
      number: '2',
      floorNumber: 1,
      capacity: 4,
      capabilities: ['AV'],
    };
    const room3 = {
      number: '3',
      floorNumber: 1,
      capacity: 5,
      capabilities: ['VC'],
    };
    const room4 = {
      number: '4',
      floorNumber: 1,
      capacity: 6,
      capabilities: [],
    };
    const room5 = {
      number: '5',
      floorNumber: 1,
      capacity: 7,
      capabilities: [],
    };
    const rooms = [room1, room2, room3, room4, room5];
    const requiredCapabilities = ['AV', 'VC'];
    const targetFloor = 1;
    const result = sortRoomsByScore(rooms, requiredCapabilities, targetFloor);
    expect(result).toEqual([room2, room3, room4, room5, room1]);
  });
  xit('should return mixed: subtle difference for one room', () => {
    const room1 = {
      number: '1',
      floorNumber: 1,
      capacity: 1,
      capabilities: ['AV'],
    };
    const room2 = {
      number: '2',
      floorNumber: 1,
      capacity: 2,
      capabilities: ['AV'],
    };
    const room3 = {
      number: '3',
      floorNumber: 1,
      capacity: 2,
      capabilities: ['AV'],
    };
    const room4 = {
      number: '4',
      floorNumber: 1,
      capacity: 2,
      capabilities: ['AV'],
    };
    const room5 = {
      number: '5',
      floorNumber: 1,
      capacity: 2,
      capabilities: ['AV'],
    };
    const rooms = [room1, room2, room3, room4, room5];
    const requiredCapabilities = ['AV', 'VC'];
    const targetFloor = 1;
    const result = sortRoomsByScore(rooms, requiredCapabilities, targetFloor);
    expect(result).toEqual([room1, room2, room3, room4, room5]);
  });
  it('should return mixed: subtle difference for one room', () => {
    const room1 = {
      number: '1',
      floorNumber: 1,
      capacity: 100,
      capabilities: [],
    };
    const room2 = {
      number: '2',
      floorNumber: 2,
      capacity: 2,
      capabilities: ['AV'],
    };
    const rooms = [room1, room2];
    const requiredCapabilities = ['AV', 'VC'];
    const targetFloor = 1;
    const result = sortRoomsByScore(rooms, requiredCapabilities, targetFloor);
    expect(result).toEqual([room2, room1]);
  });
});

describe('findAvailableRoomsByMerging', () => {
  const {
    sortRoomsByScore,
  } = require('../../lambda/algo/bookingOptions/getBookingOptions.js');
  const users = [
    [
      {
        id: 'cltn42xem009v40ld3vsly9r5',
        username: 'BookingUser1',
        name: 'Booking User1',
        email: 'bookinguser1@awschedulers.com',
        isAdmin: false,
        buildingId: 'cltn42xc0000040lduthrcte2',
        floorNumber: 1,
        Building: {
          id: 'cltn42xc0000040lduthrcte2',
          airportCode: 'YVR',
          number: 32,
          longitude: -123.1165076855913,
          latitude: 49.28132420946474,
          location: '510 W Georgia St #14, Vancouver, BC V6B 0M3',
          maxFloor: 7,
          rooms: [
            {
              id: 'cltn42xc0000140ldmtm3z7cj',
              floorNumber: 1,
              roomNumber: '101',
              roomName: 'Stanley',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc0000340ldnssgokwl',
              floorNumber: 1,
              roomNumber: '404',
              roomName: 'Lighthouse',
              capacity: 18,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc0000440ldkvt3ex0i',
              floorNumber: 1,
              roomNumber: '405',
              roomName: 'Earles Casual',
              capacity: 4,
              AV: false,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000540ldby43ytew',
              floorNumber: 1,
              roomNumber: '406',
              roomName: 'Riley',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000640ldjs2ygam8',
              floorNumber: 2,
              roomNumber: '101',
              roomName: 'Yaletown',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000740ldllh8xy1r',
              floorNumber: 2,
              roomNumber: '102',
              roomName: 'Kerrisdale',
              capacity: 6,
              AV: false,
              VC: false,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000840ldz0bflesp',
              floorNumber: 2,
              roomNumber: '103',
              roomName: 'Gastown',
              capacity: 16,
              AV: false,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000940ldl59rx9ib',
              floorNumber: 2,
              roomNumber: '404',
              roomName: 'Killarney',
              capacity: 18,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000a40ld1gwyvqnt',
              floorNumber: 2,
              roomNumber: '405',
              roomName: 'Grandview Casual',
              capacity: 5,
              AV: false,
              VC: false,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000b40ld1dlgxhtd',
              floorNumber: 2,
              roomNumber: '406',
              roomName: 'Marpole',
              capacity: 10,
              AV: false,
              VC: false,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000c40ldaey1bhuc',
              floorNumber: 3,
              roomNumber: '101',
              roomName: 'Chickadee',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000d40ldteo1z2zf',
              floorNumber: 3,
              roomNumber: '102',
              roomName: 'Reservoir',
              capacity: 6,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000e40ldvdna8naj',
              floorNumber: 3,
              roomNumber: '103',
              roomName: 'Thompson',
              capacity: 16,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000f40ld5xcs30oz',
              floorNumber: 3,
              roomNumber: '404',
              roomName: 'Brockton',
              capacity: 18,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000g40ld2de6mnk0',
              floorNumber: 3,
              roomNumber: '405',
              roomName: 'Kinglet Casual',
              capacity: 5,
              AV: false,
              VC: false,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000h40ld2r5dwn4g',
              floorNumber: 3,
              roomNumber: '406',
              roomName: 'Ravine',
              capacity: 10,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000i40ld3ook2xfh',
              floorNumber: 4,
              roomNumber: '1',
              roomName: 'Interview',
              capacity: 4,
              AV: false,
              VC: false,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000j40ldoi6qu1v2',
              floorNumber: 4,
              roomNumber: '101',
              roomName: 'Interview',
              capacity: 4,
              AV: false,
              VC: false,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000k40ldyidi3ozt',
              floorNumber: 4,
              roomNumber: '203',
              roomName: 'English Bay Combinable',
              capacity: 38,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000l40ldd1s1zmxr',
              floorNumber: 4,
              roomNumber: '204',
              roomName: 'Sunset Combinable',
              capacity: 38,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000m40ldsuwayvbk',
              floorNumber: 4,
              roomNumber: '3',
              roomName: 'Jericho',
              capacity: 26,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000n40lduba3ajbu',
              floorNumber: 5,
              roomNumber: '101',
              roomName: 'Sockeye',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000o40ld2cj7sj8y',
              floorNumber: 5,
              roomNumber: '102',
              roomName: 'Coho',
              capacity: 6,
              AV: false,
              VC: false,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000p40ldm25wwm2b',
              floorNumber: 5,
              roomNumber: '103',
              roomName: 'Chinook',
              capacity: 16,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000q40ldyjq5epxp',
              floorNumber: 5,
              roomNumber: '403',
              roomName: '',
              capacity: 14,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000r40ldpcjszs0a',
              floorNumber: 5,
              roomNumber: '404',
              roomName: 'Char',
              capacity: 18,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000s40ldqs7hr9ci',
              floorNumber: 5,
              roomNumber: '405',
              roomName: 'Steelhead Casual',
              capacity: 5,
              AV: false,
              VC: false,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000t40ldftacveav',
              floorNumber: 5,
              roomNumber: '406',
              roomName: 'Kokanee',
              capacity: 10,
              AV: false,
              VC: false,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000u40ld39tzngfb',
              floorNumber: 6,
              roomNumber: '101',
              roomName: 'Okanagan',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000v40ld7p86pacz',
              floorNumber: 6,
              roomNumber: '102',
              roomName: 'Buntzen',
              capacity: 6,
              AV: false,
              VC: false,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000w40ldzl9f5nsg',
              floorNumber: 6,
              roomNumber: '103',
              roomName: 'Elfin',
              capacity: 16,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000x40ldlxe466w8',
              floorNumber: 6,
              roomNumber: '403',
              roomName: 'Babine',
              capacity: 14,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000y40ldj9hqqasg',
              floorNumber: 6,
              roomNumber: '404',
              roomName: 'Ootsa',
              capacity: 18,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1000z40ldxwa91jq6',
              floorNumber: 6,
              roomNumber: '405',
              roomName: 'Sprott Casual',
              capacity: 5,
              AV: false,
              VC: false,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1001040ld138i2v2r',
              floorNumber: 6,
              roomNumber: '406',
              roomName: 'Kootenay',
              capacity: 10,
              AV: false,
              VC: false,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1001140ldh4ozmo0t',
              floorNumber: 7,
              roomNumber: '1',
              roomName: 'Eagle',
              capacity: 10,
              AV: false,
              VC: false,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1001240ldn64g3nbq',
              floorNumber: 7,
              roomNumber: '101',
              roomName: 'Lynx',
              capacity: 18,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1001340ldkmqdus8w',
              floorNumber: 7,
              roomNumber: '404',
              roomName: 'Kermode',
              capacity: 4,
              AV: false,
              VC: false,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1001440ldxlxnwuxo',
              floorNumber: 7,
              roomNumber: '405',
              roomName: 'Orca',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1001540ld777wh31m',
              floorNumber: 7,
              roomNumber: '406',
              roomName: 'Moose Casual',
              capacity: 5,
              AV: false,
              VC: false,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
            {
              id: 'cltn42xc1001640ld7r32uh3u',
              floorNumber: 7,
              roomNumber: '407',
              roomName: 'Raccoon',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xc0000040lduthrcte2',
            },
          ],
        },
      },
      {
        id: 'cltn42xem009w40ldbna2alt8',
        username: 'BookingUser2',
        name: 'Booking User2',
        email: 'bookinguser2@awschedulers.com',
        isAdmin: false,
        buildingId: 'cltn42xce001740ldjcrh6iyn',
        floorNumber: 2,
        Building: {
          id: 'cltn42xce001740ldjcrh6iyn',
          airportCode: 'YVR',
          number: 41,
          longitude: -123.1138077983486,
          latitude: 49.28176318729041,
          location: '402 Dunsmuir St, Vancouver, BC V6B 1X4',
          maxFloor: 9,
          rooms: [
            {
              id: 'cltn42xce001840ldc4c4ji8n',
              floorNumber: 1,
              roomNumber: '401',
              roomName: 'Interview Room',
              capacity: 4,
              AV: false,
              VC: false,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001940lde0pt6ssv',
              floorNumber: 2,
              roomNumber: '1',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001a40ldtb5qtss1',
              floorNumber: 2,
              roomNumber: '101',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001b40ldcqplrqn2',
              floorNumber: 2,
              roomNumber: '103',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001c40lducqpamtt',
              floorNumber: 2,
              roomNumber: '104',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001d40ldfwd42cho',
              floorNumber: 2,
              roomNumber: '105',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001e40ld2r7ou0p7',
              floorNumber: 2,
              roomNumber: '2',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001f40lddzje70yy',
              floorNumber: 2,
              roomNumber: '201',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001g40ldh8mdsp9k',
              floorNumber: 2,
              roomNumber: '204',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001h40ldol936tl1',
              floorNumber: 2,
              roomNumber: '401',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001i40ldiw239r8w',
              floorNumber: 3,
              roomNumber: '1',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001j40ldmycebpef',
              floorNumber: 3,
              roomNumber: '101',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001k40ld4n6mwo7v',
              floorNumber: 3,
              roomNumber: '102',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001l40ldsdu3350i',
              floorNumber: 3,
              roomNumber: '103',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001m40ldex01t4gk',
              floorNumber: 3,
              roomNumber: '104',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001n40ld6ydl8l9g',
              floorNumber: 3,
              roomNumber: '2',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001o40ldeitrc2u8',
              floorNumber: 3,
              roomNumber: '201',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001p40ldfeh0lv1o',
              floorNumber: 3,
              roomNumber: '301',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001q40ldljo62ftp',
              floorNumber: 3,
              roomNumber: '302',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001r40ld7totddiw',
              floorNumber: 3,
              roomNumber: '4',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001s40ldl86y8bet',
              floorNumber: 4,
              roomNumber: '1',
              roomName: '',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001t40ldr4l3axbo',
              floorNumber: 4,
              roomNumber: '101',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001u40ld0gt5wobv',
              floorNumber: 4,
              roomNumber: '102',
              roomName: 'Conference Room',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001v40ldp6ujmg4s',
              floorNumber: 4,
              roomNumber: '103',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001w40ldpyzmsuxf',
              floorNumber: 4,
              roomNumber: '104',
              roomName: '',
              capacity: 18,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001x40ldv8idt6dm',
              floorNumber: 4,
              roomNumber: '2',
              roomName: '',
              capacity: 6,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001y40ld6yjlkaqm',
              floorNumber: 4,
              roomNumber: '201',
              roomName: '',
              capacity: 6,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce001z40ldou5eclyp',
              floorNumber: 4,
              roomNumber: '202',
              roomName: '',
              capacity: 14,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002040ldvlprzkqy',
              floorNumber: 4,
              roomNumber: '3',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002140ld8h0h4c06',
              floorNumber: 4,
              roomNumber: '301',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002240ldf0v5412m',
              floorNumber: 4,
              roomNumber: '302',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002340ldxp98hhe7',
              floorNumber: 5,
              roomNumber: '102',
              roomName: '',
              capacity: 5,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002440ld161je7f8',
              floorNumber: 5,
              roomNumber: '2',
              roomName: '',
              capacity: 14,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002540ld27659pv1',
              floorNumber: 5,
              roomNumber: '201',
              roomName: '',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002640ldosavs9dl',
              floorNumber: 5,
              roomNumber: '202',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002740ldgltl3g0f',
              floorNumber: 5,
              roomNumber: '203',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002840ldllxrll06',
              floorNumber: 5,
              roomNumber: '204',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002940lde9km5qgm',
              floorNumber: 5,
              roomNumber: '205',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002a40ldxugbbz2u',
              floorNumber: 5,
              roomNumber: '206',
              roomName: '',
              capacity: 18,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002b40ldjbh04yym',
              floorNumber: 5,
              roomNumber: '3',
              roomName: '',
              capacity: 6,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002c40ld5w0c219t',
              floorNumber: 5,
              roomNumber: '301',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002d40ldk6m8f338',
              floorNumber: 6,
              roomNumber: '1',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002e40ld4iyufgm3',
              floorNumber: 6,
              roomNumber: '101',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002f40ldjlx9f0c0',
              floorNumber: 6,
              roomNumber: '102',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002g40ldog20c3u5',
              floorNumber: 6,
              roomNumber: '103',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002h40lda7f3919o',
              floorNumber: 6,
              roomNumber: '301',
              roomName: '',
              capacity: 6,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002i40ldlgclpn4l',
              floorNumber: 7,
              roomNumber: '1',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002j40ldj1t2i15r',
              floorNumber: 7,
              roomNumber: '101',
              roomName: '',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002k40ldur2ddi84',
              floorNumber: 7,
              roomNumber: '102',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002l40ldw2tv3svs',
              floorNumber: 7,
              roomNumber: '103',
              roomName: '',
              capacity: 18,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002m40ld2ps41aut',
              floorNumber: 7,
              roomNumber: '2',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xce002n40ldgueiduxc',
              floorNumber: 7,
              roomNumber: '201',
              roomName: '',
              capacity: 14,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xcf002o40ldy0227hgt',
              floorNumber: 7,
              roomNumber: '3',
              roomName: '',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xcf002p40ld3v8skkj9',
              floorNumber: 7,
              roomNumber: '301',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xcf002q40ldstepfsgj',
              floorNumber: 7,
              roomNumber: '304',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xcf002r40ldzkeglffs',
              floorNumber: 7,
              roomNumber: '4',
              roomName: '',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xcf002s40ld1y27qm91',
              floorNumber: 8,
              roomNumber: '3',
              roomName: 'Boardroom',
              capacity: 22,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xcf002t40ldldg8yu34',
              floorNumber: 8,
              roomNumber: '301',
              roomName: 'Boardroom Combinable',
              capacity: 30,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xcf002u40ldnzpch6bq',
              floorNumber: 8,
              roomNumber: '302',
              roomName: 'Boardroom Combinable',
              capacity: 30,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xcf002v40ldid9ti2bv',
              floorNumber: 9,
              roomNumber: '1',
              roomName: '',
              capacity: 10,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xcf002w40ldilzlmoll',
              floorNumber: 9,
              roomNumber: '101',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xcf002x40ld29g4dplg',
              floorNumber: 9,
              roomNumber: '102',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xcf002y40ldu6eb79a4',
              floorNumber: 9,
              roomNumber: '103',
              roomName: '',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xcf002z40ldqrc3um8c',
              floorNumber: 9,
              roomNumber: '201',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xcf003040ldas5k2331',
              floorNumber: 9,
              roomNumber: '202',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
            {
              id: 'cltn42xcf003140ldlzhtb8ab',
              floorNumber: 9,
              roomNumber: '3',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xce001740ldjcrh6iyn',
            },
          ],
        },
      },
      {
        id: 'cltn42xem009x40ld716y257p',
        username: 'BookingUser3',
        name: 'Booking User3',
        email: 'bookinguser3@awschedulers.com',
        isAdmin: false,
        buildingId: 'cltn42xd8004a40ldc9lsmlf6',
        floorNumber: 3,
        Building: {
          id: 'cltn42xd8004a40ldc9lsmlf6',
          airportCode: 'YVR',
          number: 63,
          longitude: -123.1190831312691,
          latitude: 49.28649403868768,
          location: '555 Burrard St, Vancouver, BC V7X 1M8',
          maxFloor: 5,
          rooms: [
            {
              id: 'cltn42xd8004b40ld0sfrgsyj',
              floorNumber: 1,
              roomNumber: '1',
              roomName: 'Interview Room',
              capacity: 3,
              AV: false,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004c40ldhkmmkkdy',
              floorNumber: 1,
              roomNumber: '101',
              roomName: 'Interview Room',
              capacity: 3,
              AV: false,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004d40ld3hu3ls08',
              floorNumber: 1,
              roomNumber: '302',
              roomName: 'Boardroom',
              capacity: 30,
              AV: true,
              VC: true,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004e40ldagit5l9a',
              floorNumber: 1,
              roomNumber: '4',
              roomName: 'Boardroom',
              capacity: 20,
              AV: true,
              VC: true,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004f40ldqfldaefh',
              floorNumber: 1,
              roomNumber: '401',
              roomName: '',
              capacity: 10,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004g40ldv4tk7c7i',
              floorNumber: 1,
              roomNumber: '402',
              roomName: '',
              capacity: 20,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004h40ldb21acp4r',
              floorNumber: 1,
              roomNumber: '403',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004i40ldqku726wq',
              floorNumber: 1,
              roomNumber: '404',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004j40ldzd29v0uv',
              floorNumber: 2,
              roomNumber: '102',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004k40ldk0eqfpq8',
              floorNumber: 2,
              roomNumber: '103',
              roomName: '',
              capacity: 6,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004l40lde3eq8xev',
              floorNumber: 2,
              roomNumber: '2',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004m40ld1c1aqtj5',
              floorNumber: 2,
              roomNumber: '3',
              roomName: '',
              capacity: 8,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004n40ldhqn69w2e',
              floorNumber: 2,
              roomNumber: '301',
              roomName: '',
              capacity: 10,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004o40lddavlbcme',
              floorNumber: 3,
              roomNumber: '1',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004p40ldvd02gork',
              floorNumber: 3,
              roomNumber: '101',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004q40ldoouviobj',
              floorNumber: 3,
              roomNumber: '103',
              roomName: '',
              capacity: 8,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004r40ldn0tdh3nl',
              floorNumber: 3,
              roomNumber: '201',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004s40ldobt0l83j',
              floorNumber: 3,
              roomNumber: '203',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004t40ld1grg8cz3',
              floorNumber: 3,
              roomNumber: '301',
              roomName: '',
              capacity: 14,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004u40ldfj5nc1eg',
              floorNumber: 3,
              roomNumber: '4',
              roomName: '',
              capacity: 14,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004v40ldara8azwv',
              floorNumber: 4,
              roomNumber: '1',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004w40ldw407joxu',
              floorNumber: 4,
              roomNumber: '101',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004x40ldxfdad2na',
              floorNumber: 4,
              roomNumber: '103',
              roomName: '',
              capacity: 8,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004y40ldpj5f626f',
              floorNumber: 4,
              roomNumber: '201',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8004z40ld1teqnfpm',
              floorNumber: 4,
              roomNumber: '203',
              roomName: '',
              capacity: 14,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8005040ldca5huszo',
              floorNumber: 4,
              roomNumber: '301',
              roomName: '',
              capacity: 14,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8005140ldv51h76oj',
              floorNumber: 4,
              roomNumber: '4',
              roomName: '',
              capacity: 14,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8005240ldh1s9dm6l',
              floorNumber: 5,
              roomNumber: '1',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8005340ldy0uzifap',
              floorNumber: 5,
              roomNumber: '201',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd8005440ldz9669e7h',
              floorNumber: 5,
              roomNumber: '203',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd9005540ld0rmrwbwf',
              floorNumber: 5,
              roomNumber: '301',
              roomName: '',
              capacity: 14,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
            {
              id: 'cltn42xd9005640ld7rgxfubl',
              floorNumber: 5,
              roomNumber: '4',
              roomName: '',
              capacity: 14,
              AV: true,
              VC: false,
              buildingId: 'cltn42xd8004a40ldc9lsmlf6',
            },
          ],
        },
      },
      {
        id: 'cltn42xem009y40ldqc7q92gd',
        username: 'BookingUser4',
        name: 'Booking User4',
        email: 'bookinguser4@awschedulers.com',
        isAdmin: false,
        buildingId: 'cltn42xcv003240ldi2zk37o0',
        floorNumber: 4,
        Building: {
          id: 'cltn42xcv003240ldi2zk37o0',
          airportCode: 'YVR',
          number: 74,
          longitude: -123.1142284249134,
          latitude: 49.28041113710248,
          location: '399 W Georgia St, Vancouver, BC V6B 1Z1',
          maxFloor: 7,
          rooms: [
            {
              id: 'cltn42xcv003340ldrz7s25wr',
              floorNumber: 1,
              roomNumber: '1',
              roomName: 'Hollyburn',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcv003440ldth6w6mlz',
              floorNumber: 1,
              roomNumber: '101',
              roomName: 'Strachan',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcv003540ld4rl94qkh',
              floorNumber: 1,
              roomNumber: '205',
              roomName: 'Burwell',
              capacity: 10,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcv003640ldig7zle06',
              floorNumber: 1,
              roomNumber: '3',
              roomName: 'Black Tusk',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcv003740ld2mk0nav8',
              floorNumber: 1,
              roomNumber: '301',
              roomName: 'Lions',
              capacity: 16,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcv003840ld2ljtvkdm',
              floorNumber: 1,
              roomNumber: '302',
              roomName: 'Brunswick Boardroom Combinable',
              capacity: 22,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcv003940ldmzylwe37',
              floorNumber: 1,
              roomNumber: '303',
              roomName: 'Capilano Boardroom Combinable',
              capacity: 22,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcv003a40ldno4tcfsc',
              floorNumber: 1,
              roomNumber: '4',
              roomName: 'Bugaboo',
              capacity: 5,
              AV: false,
              VC: false,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003b40ldipw06uj5',
              floorNumber: 1,
              roomNumber: '401',
              roomName: 'Seymour',
              capacity: 5,
              AV: false,
              VC: false,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003c40ld52qvk0j5',
              floorNumber: 2,
              roomNumber: '1',
              roomName: 'Grouse',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003d40ld1dnmx91g',
              floorNumber: 2,
              roomNumber: '101',
              roomName: 'Cronin',
              capacity: 6,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003e40ldb8rtut5e',
              floorNumber: 2,
              roomNumber: '402',
              roomName: 'Castlegar',
              capacity: 14,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003f40ld8yv4t2x4',
              floorNumber: 3,
              roomNumber: '1',
              roomName: 'Tantalus',
              capacity: 6,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003g40ld3qfn9a9n',
              floorNumber: 3,
              roomNumber: '301',
              roomName: 'Lillooet',
              capacity: 6,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003h40ld3hz04qjj',
              floorNumber: 3,
              roomNumber: '302',
              roomName: 'Coliseum',
              capacity: 5,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003i40ldri8lv16v',
              floorNumber: 3,
              roomNumber: '305',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003j40ldydt4id9y',
              floorNumber: 3,
              roomNumber: '306',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003k40ldtzzchtci',
              floorNumber: 4,
              roomNumber: '1',
              roomName: 'Harrison',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003l40ldumknmm2f',
              floorNumber: 4,
              roomNumber: '201',
              roomName: 'Shuswap',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003m40ldczi740it',
              floorNumber: 4,
              roomNumber: '202',
              roomName: 'Garibaldi',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003n40ldm1ly2bmx',
              floorNumber: 4,
              roomNumber: '3',
              roomName: 'Alice',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003o40ldh6yeck78',
              floorNumber: 4,
              roomNumber: '401',
              roomName: 'Deer',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003p40ldwkytvi0f',
              floorNumber: 4,
              roomNumber: '402',
              roomName: 'Cultus',
              capacity: 14,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003q40ldzjjk75sj',
              floorNumber: 5,
              roomNumber: '1',
              roomName: 'Amber',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003r40ld9f20rpfj',
              floorNumber: 5,
              roomNumber: '101',
              roomName: 'Jade',
              capacity: 6,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003s40ld7uwqar6f',
              floorNumber: 5,
              roomNumber: '201',
              roomName: 'Opal',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003t40ldn4bupse6',
              floorNumber: 5,
              roomNumber: '202',
              roomName: 'Quartz',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003u40ldc1l4tl6b',
              floorNumber: 5,
              roomNumber: '3',
              roomName: 'Topaz',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003v40ldqvl6y6xz',
              floorNumber: 5,
              roomNumber: '401',
              roomName: 'Emerald',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003w40ldch23tfc0',
              floorNumber: 5,
              roomNumber: '402',
              roomName: 'Ammolite',
              capacity: 14,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003x40ld2i49jfur',
              floorNumber: 6,
              roomNumber: '1',
              roomName: 'Fir',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003y40ldmgr58b2q',
              floorNumber: 6,
              roomNumber: '201',
              roomName: 'Willow',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw003z40ldt16e7gs4',
              floorNumber: 6,
              roomNumber: '202',
              roomName: 'Spruce',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw004040ld5ts3bi6f',
              floorNumber: 6,
              roomNumber: '3',
              roomName: 'Oak',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw004140ldd44qyqw6',
              floorNumber: 6,
              roomNumber: '401',
              roomName: 'Pine',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw004240ldz27msp5c',
              floorNumber: 6,
              roomNumber: '402',
              roomName: 'Cedar',
              capacity: 14,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw004340ldwfbkdy9y',
              floorNumber: 7,
              roomNumber: '1',
              roomName: 'Waterfront',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw004440ld4rw1zr9y',
              floorNumber: 7,
              roomNumber: '101',
              roomName: 'Vancouver',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw004540ldt8624z4r',
              floorNumber: 7,
              roomNumber: '102',
              roomName: 'Olympic',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw004640ldlbpq90hk',
              floorNumber: 7,
              roomNumber: '3',
              roomName: 'Oakridge',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw004740ldirixquo9',
              floorNumber: 7,
              roomNumber: '301',
              roomName: 'Langara',
              capacity: 10,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw004840ldhowoejoz',
              floorNumber: 7,
              roomNumber: '401',
              roomName: 'Broadway',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
            {
              id: 'cltn42xcw004940ldyh7sa3m3',
              floorNumber: 7,
              roomNumber: '402',
              roomName: 'Granville',
              capacity: 14,
              AV: true,
              VC: true,
              buildingId: 'cltn42xcv003240ldi2zk37o0',
            },
          ],
        },
      },
      {
        id: 'cltn42xem009z40ld368adadh',
        username: 'BookingUser5',
        name: 'Booking User5',
        email: 'bookinguser5@awschedulers.com',
        isAdmin: false,
        buildingId: 'cltn42xdi005740ld603mi3qy',
        floorNumber: 5,
        Building: {
          id: 'cltn42xdi005740ld603mi3qy',
          airportCode: 'YVR',
          number: 73,
          longitude: -123.1157544701559,
          latitude: 49.28573544591995,
          location: '2400-475 Howe St, Vancouver, BC V6C 2B3',
          maxFloor: 11,
          rooms: [
            {
              id: 'cltn42xdj005840ldxz53juzh',
              floorNumber: 1,
              roomNumber: '308',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005940ldk2h3f4zm',
              floorNumber: 1,
              roomNumber: '309',
              roomName: '',
              capacity: 10,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005a40ldkudsd3th',
              floorNumber: 1,
              roomNumber: '31',
              roomName: '',
              capacity: 20,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005b40ldo2zfvu4x',
              floorNumber: 1,
              roomNumber: '311',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005c40ldj4x2pyjd',
              floorNumber: 1,
              roomNumber: '403',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005d40ld5c9dyhg3',
              floorNumber: 1,
              roomNumber: '404',
              roomName: '',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005e40ldmfop9aus',
              floorNumber: 2,
              roomNumber: '307',
              roomName: '',
              capacity: 10,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005f40ldha0amfx1',
              floorNumber: 2,
              roomNumber: '308',
              roomName: '',
              capacity: 20,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005g40ldl67943u1',
              floorNumber: 2,
              roomNumber: '309',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005h40ldcckjboe1',
              floorNumber: 2,
              roomNumber: '403',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005i40ldft1yiavu',
              floorNumber: 2,
              roomNumber: '404',
              roomName: '',
              capacity: 10,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005j40ldkepyhgkf',
              floorNumber: 3,
              roomNumber: '321',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005k40ldemdww3b2',
              floorNumber: 3,
              roomNumber: '327',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005l40ldmphxigqa',
              floorNumber: 3,
              roomNumber: '328',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005m40ldyhjpzzoc',
              floorNumber: 3,
              roomNumber: '329',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005n40ldbt6k27st',
              floorNumber: 3,
              roomNumber: '332',
              roomName: 'Training Room Combinable',
              capacity: 30,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005o40ldkgsi6jy9',
              floorNumber: 3,
              roomNumber: '333',
              roomName: 'Training Room Combinable',
              capacity: 30,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005p40ld084rnezf',
              floorNumber: 3,
              roomNumber: '407',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005q40ldjymjp8is',
              floorNumber: 3,
              roomNumber: '408',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005r40ldj2wuishk',
              floorNumber: 3,
              roomNumber: '409',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005s40ldnfkprftb',
              floorNumber: 3,
              roomNumber: '41',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005t40ldl5w9k99p',
              floorNumber: 3,
              roomNumber: '42',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005u40ldl3h3gayc',
              floorNumber: 4,
              roomNumber: '3',
              roomName: '',
              capacity: 10,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005v40ldxfan8vxu',
              floorNumber: 4,
              roomNumber: '309',
              roomName: '',
              capacity: 10,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005w40ldxr5jf3at',
              floorNumber: 4,
              roomNumber: '313',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005x40ldi72awv1l',
              floorNumber: 4,
              roomNumber: '315',
              roomName: '',
              capacity: 16,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005y40lds9tkyesy',
              floorNumber: 4,
              roomNumber: '316',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj005z40ldqkn3g1y8',
              floorNumber: 4,
              roomNumber: '4',
              roomName: '',
              capacity: 10,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006040ld21qew84t',
              floorNumber: 4,
              roomNumber: '413',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006140ldx53chwm5',
              floorNumber: 4,
              roomNumber: '414',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006240ldhdp8adkr',
              floorNumber: 4,
              roomNumber: '415',
              roomName: 'Training Room Combinable',
              capacity: 30,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006340ldgrm5z859',
              floorNumber: 4,
              roomNumber: '416',
              roomName: 'Training Room Combinable',
              capacity: 30,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006440ldg8x3d70c',
              floorNumber: 5,
              roomNumber: '3',
              roomName: 'Training Room Combinable',
              capacity: 30,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006540ld16rze22u',
              floorNumber: 5,
              roomNumber: '301',
              roomName: 'Training Room Combinable',
              capacity: 30,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006640ldpm874ktl',
              floorNumber: 5,
              roomNumber: '306',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006740ld28r9u4ps',
              floorNumber: 5,
              roomNumber: '313',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006840ld3ncxuq8p',
              floorNumber: 5,
              roomNumber: '314',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006940ldx2cviref',
              floorNumber: 5,
              roomNumber: '4',
              roomName: '',
              capacity: 16,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006a40ld5gx20q3q',
              floorNumber: 5,
              roomNumber: '401',
              roomName: '',
              capacity: 20,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006b40ldjas03508',
              floorNumber: 5,
              roomNumber: '42',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006c40ldw9fjni2m',
              floorNumber: 5,
              roomNumber: '421',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006d40ld78ddgslx',
              floorNumber: 5,
              roomNumber: '422',
              roomName: '',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006e40ldibjzz2df',
              floorNumber: 6,
              roomNumber: '3',
              roomName: 'Training Room Combinable',
              capacity: 30,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006f40ldpdw9ozeg',
              floorNumber: 6,
              roomNumber: '301',
              roomName: 'Training Room Combinable',
              capacity: 30,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006g40ldrk2omsim',
              floorNumber: 6,
              roomNumber: '302',
              roomName: 'Training Room',
              capacity: 30,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006h40ldmltr11rv',
              floorNumber: 6,
              roomNumber: '303',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006i40lde8ahvmd4',
              floorNumber: 6,
              roomNumber: '304',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006j40ldp5ym90vz',
              floorNumber: 6,
              roomNumber: '306',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006k40ldxjizx0gi',
              floorNumber: 6,
              roomNumber: '314',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006l40ldn5j1mhb5',
              floorNumber: 6,
              roomNumber: '315',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006m40ldb6sriiyl',
              floorNumber: 6,
              roomNumber: '316',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006n40ldhky94mus',
              floorNumber: 6,
              roomNumber: '4',
              roomName: '',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006o40ld2d6u56bo',
              floorNumber: 6,
              roomNumber: '401',
              roomName: '',
              capacity: 18,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006p40ldx6x6nftm',
              floorNumber: 6,
              roomNumber: '419',
              roomName: 'Training Room',
              capacity: 30,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006q40ldgsy19l7b',
              floorNumber: 7,
              roomNumber: '3',
              roomName: '',
              capacity: 20,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006r40ldkgaxn79l',
              floorNumber: 7,
              roomNumber: '305',
              roomName: '',
              capacity: 14,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006s40ld3qc4vbeb',
              floorNumber: 7,
              roomNumber: '312',
              roomName: '',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006t40ldlmnz282v',
              floorNumber: 7,
              roomNumber: '313',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006u40ldaowanpq1',
              floorNumber: 7,
              roomNumber: '314',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006v40ldtll9rtpk',
              floorNumber: 7,
              roomNumber: '401',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006w40ldb50jf6sy',
              floorNumber: 7,
              roomNumber: '402',
              roomName: '',
              capacity: 14,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006x40ldhy4mt3ma',
              floorNumber: 7,
              roomNumber: '403',
              roomName: '',
              capacity: 10,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006y40ldfilz88ba',
              floorNumber: 7,
              roomNumber: '404',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj006z40ldqy1w2h3h',
              floorNumber: 7,
              roomNumber: '405',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007040ld7jnao56o',
              floorNumber: 7,
              roomNumber: '424',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007140ldhzph1ofv',
              floorNumber: 8,
              roomNumber: '3',
              roomName: '',
              capacity: 20,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007240ldep8tult5',
              floorNumber: 8,
              roomNumber: '312',
              roomName: '',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007340ldn0ylsdyy',
              floorNumber: 8,
              roomNumber: '313',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007440ldc8uok8h6',
              floorNumber: 8,
              roomNumber: '314',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007540ldggsen4g9',
              floorNumber: 8,
              roomNumber: '401',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007640ldwci539zm',
              floorNumber: 8,
              roomNumber: '402',
              roomName: '',
              capacity: 14,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007740ldwo9uv9z1',
              floorNumber: 8,
              roomNumber: '403',
              roomName: '',
              capacity: 10,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007840lduiw29xsq',
              floorNumber: 8,
              roomNumber: '404',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007940ldyyrl67e0',
              floorNumber: 8,
              roomNumber: '405',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007a40ld6u0r8qc1',
              floorNumber: 8,
              roomNumber: '424',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007b40ldwjdrhi4t',
              floorNumber: 9,
              roomNumber: '3',
              roomName: '',
              capacity: 20,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007c40ldd9r275fg',
              floorNumber: 9,
              roomNumber: '305',
              roomName: '',
              capacity: 14,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007d40ldixkvrxcn',
              floorNumber: 9,
              roomNumber: '312',
              roomName: '',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007e40ldh7afztms',
              floorNumber: 9,
              roomNumber: '313',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007f40ld644cxkh2',
              floorNumber: 9,
              roomNumber: '314',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007g40ldhulza64l',
              floorNumber: 9,
              roomNumber: '401',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007h40ldb7tlgagm',
              floorNumber: 9,
              roomNumber: '402',
              roomName: '',
              capacity: 14,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007i40ldpi8aazxd',
              floorNumber: 9,
              roomNumber: '403',
              roomName: '',
              capacity: 10,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007j40ldzz8zfhui',
              floorNumber: 9,
              roomNumber: '404',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007k40ldpwnrjol7',
              floorNumber: 9,
              roomNumber: '405',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007l40ld77sbp7fi',
              floorNumber: 9,
              roomNumber: '424',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007m40ldojzumv67',
              floorNumber: 10,
              roomNumber: '3',
              roomName: '',
              capacity: 20,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007n40ld2yjl63wf',
              floorNumber: 10,
              roomNumber: '312',
              roomName: '',
              capacity: 8,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007o40ldal0377df',
              floorNumber: 10,
              roomNumber: '313',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007p40ldk8obf0n2',
              floorNumber: 10,
              roomNumber: '314',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007q40ld3yx7vhkr',
              floorNumber: 10,
              roomNumber: '401',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007r40ld4c9lebju',
              floorNumber: 10,
              roomNumber: '402',
              roomName: '',
              capacity: 14,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007s40ldrodwb2lf',
              floorNumber: 10,
              roomNumber: '403',
              roomName: '',
              capacity: 10,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007t40ldbmnp19ba',
              floorNumber: 10,
              roomNumber: '404',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007u40ldme23gyx5',
              floorNumber: 10,
              roomNumber: '405',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007v40ld38e6ic08',
              floorNumber: 10,
              roomNumber: '424',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007w40ldshtoc60s',
              floorNumber: 11,
              roomNumber: '3',
              roomName: '',
              capacity: 20,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007x40ldofjru518',
              floorNumber: 11,
              roomNumber: '314',
              roomName: '',
              capacity: 12,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007y40ldf8c0xqze',
              floorNumber: 11,
              roomNumber: '403',
              roomName: '',
              capacity: 10,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
            {
              id: 'cltn42xdj007z40ld9d2an5k7',
              floorNumber: 11,
              roomNumber: '404',
              roomName: '',
              capacity: 4,
              AV: true,
              VC: true,
              buildingId: 'cltn42xdi005740ld603mi3qy',
            },
          ],
        },
      },
    ],
  ];
});
